sudo: required

language: java

services:
        - docker

before_install:
  - docker build -t tropars/unit-tests .
  - docker run tropars/unit-tests

after_success:
  - docker log  in -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push tropars/unit-tests
